### ISSUE TITLE
Audible click with release amp envelope

### ISSUE THREAD

**Issue by IrwinKwan** [AudioKit/AnalogSynthX#2]
I’m hearing audible clicks if amp envelopes are turned up. Going to try to get a screen of current settings but if you have a basic patch with DCO1 and open the envelope all the way, then turn up the release and play Middle C, you can hear clicks when the oscilloscope is just about to stop vibrating.

IPad Air 1st gen latest iOS

https://www.dropbox.com/s/kil3jp7s68afhoc/audiosynth-x-click.png

**Comment by IrwinKwan** [comment]
I’m hearing audible clicks if amp envelopes are turned up. Going to try to get a screen of current settings but if you have a basic patch with DCO1 and open the envelope all the way, then turn up the release and play Middle C, you can hear clicks when the oscilloscope is just about to stop vibrating.

IPad Air 1st gen latest iOS

**Comment by aure** [comment]
I'm sorry that you're having a click with AudioKit Synth One, but this is the repo for AudioKIt's Analogy Synth X, a completely different app.  The code for AudioKit Synth One will be made public in early July.
